CREATE TABLE USER_INFO AS (SELECT * FROM keykholt.PUBLIC_USER_INFORMATION);
CREATE TABLE FRIEND_INFO AS (SELECT * FROM keykholt.PUBLIC_ARE_FRIENDS);
CREATE TABLE PHOTO_INFO AS (SELECT * FROM keykholt.PUBLIC_PHOTO_INFORMATION);
CREATE TABLE TAG_INFO AS (SELECT * FROM keykholt.PUBLIC_TAG_INFORMATION);
CREATE TABLE EVENT_INFO AS (SELECT * FROM keykholt.PUBLIC_EVENT_INFORMATION);