CREATE TABLE VIEW_USER_INFORMATION(
	USER_ID VARCHAR2(100),
	FIRST_NAME VARCHAR2(100),
	LAST_NAME VARCHAR2(100),
	YEAR_OF_BIRTH NUMBER(38),
	MONTH_OF_BIRTH NUMBER(38),
	DAY_OF_BIRTH NUMBER(38),
	GENDER VARCHAR2(100),
	CURRENT_CITY VARCHAR2(100),
	CURRENT_STATE VARCHAR2(100),
	CURRENT_COUNTRY VARCHAR2(100),
	HOMETOWN_CITY VARCHAR2(100),
	HOMETOWN_STATE VARCHAR2(100),
	HOMETOWN_COUNTRY VARCHAR2(100),
	INSTITUTION_NAME VARCHAR2(100),
	PROGRAM_YEAR NUMBER(38),
	PROGRAM_CONCENTRATION CHAR(100),
	PROGRAM_DEGREE VARCHAR2(100)
);

CREATE TABLE VIEW_ARE_FRIENDS(
	USER1_ID VARCHAR2(100),
	USER2_ID VARCHAR2(100)
);

CREATE TABLE VIEW_PHOTO_INFORMATION(
	ALBUM_ID VARCHAR2(100),
	OWNER_ID VARCHAR2(100),
	COVER_PHOTO_ID VARCHAR2(100),
	ALBUM_NAME VARCHAR2(100),
	ALBUM_CREATED_TIME TIMESTAMP(6),
	ALBUM_MODIFIED_TIME TIMESTAMP(6),
	ALBUM_LINK VARCHAR2(2000),
	ALBUM_VISIBILITY VARCHAR2(100),
	PHOTO_ID VARCHAR2(100),
	PHOTO_CAPTION VARCHAR2(2000),
	PHOTO_CREATED_TIME TIMESTAMP(6),
	PHOTO_MODIFIED_TIME TIMESTAMP(6),
	PHOTO_LINK VARCHAR2(2000)
);

CREATE TABLE VIEW_TAG_INFORMATION(
	PHOTO_ID VARCHAR2(100),
	TAG_SUBJECT_ID VARCHAR2(100),
	TAG_CREATED_TIME TIMESTAMP(6),
	TAG_X_COORDINATE NUMBER,
	TAG_Y_COORDINATE NUMBER
);

CREATE TABLE VIEW_EVENT_INFORMATION(
	EVENT_ID VARCHAR2(100),
	EVENT_CREATOR_ID VARCHAR2(100),
	EVENT_NAME VARCHAR2(100),
	EVENT_TAGLINE VARCHAR2(1000),
	EVENT_DESCRIPTION VARCHAR2(4000),
	EVENT_HOST VARCHAR2(100),
	EVENT_TYPE VARCHAR2(100),
	EVENT_SUBTYPE VARCHAR2(100),
	EVENT_LOCATION VARCHAR2(200),
	EVENT_CITY VARCHAR2(100),
	EVENT_STATE VARCHAR2(100),
	EVENT_COUNTRY VARCHAR2(100),
	EVENT_START_TIME TIMESTAMP(6),
	EVENT_END_TIME TIMESTAMP(6)
);

INSERT INTO VIEW_USER_INFORMATION
SELECT u.user_ID USER_ID,
	u.first_name FIRST_NAME,
	u.last_name LAST_NAME,
	u.year_of_birth YEAR_OF_BIRTH,
	u.month_of_birth MONTH_OF_BIRTH,
	u.date_of_birth DAY_OF_BIRTH,
	u.gender GENDER,
	c.city CURRENT_CITY,
	c.state CURRENT_STATE,
	c.country CURRENT_COUNTRY,
	h.city HOMETOWN_CITY,
	h.state HOMETOWN_STATE,
	h.country HOMETOWN_COUNTRY,
	e.institution_name INSTITUTION_NAME,
	a.year_of_graduation PROGRAM_YEAR,
	e.concentration PROGRAM_CONCENTRATION,
	e.degree PROGRAM_DEGREE
FROM FB_User u 
LEFT JOIN Location h ON u.home_town_ID = h.location_ID
LEFT JOIN Location c ON u.current_location_ID = c.location_ID
LEFT JOIN Attended_program a ON u.user_ID = a.user_ID
LEFT JOIN Education_program e ON a.program_ID = e.program_ID;

INSERT INTO VIEW_ARE_FRIENDS
SELECT user1_ID USER1_ID, user2_ID USER2_ID
FROM Friendship;

INSERT INTO VIEW_PHOTO_INFORMATION
SELECT a.album_ID ALBUM_ID,
	a.owner_user_ID OWNER_ID,
	a.cover_photo_ID COVER_PHOTO_ID,
	a.album_name ALBUM_NAME,
	a.album_created_time ALBUM_CREATED_TIME,
	a.album_modified_time ALBUM_MODIFIED_TIME,
	a.album_link ALBUM_LINK,
	a.album_visibility ALBUM_VISIBILITY,
	p.photo_ID PHOTO_ID,
	p.photo_caption PHOTO_CAPTION,
	p.photo_created_time PHOTO_CREATED_TIME,
	p.photo_modified_time PHOTO_MODIFIED_TIME,
	p.photo_link PHOTO_LINK
FROM Photo p
LEFT JOIN Album a ON p.album_ID = a.album_ID;

INSERT INTO VIEW_TAG_INFORMATION
SELECT photo_ID PHOTO_ID,
	user_ID TAG_SUBJECT_ID,
	tag_created_time TAG_CREATED_TIME,
	tag_x_coordinate TAG_X_COORDINATE,
	tag_y_coordinate TAG_Y_COORDINATE
FROM Tag

INSERT INTO VIEW_EVENT_INFORMATION
SELECT e.Event_ID EVENT_ID,
	e.Event_creator_ID EVENT_CREATOR_ID,
	e.Event_name EVENT_NAME,
	e.Event_tagline EVENT_TAGLINE,
	e.Event_description EVENT_DESCRIPTION,
	e.Event_host EVENT_HOST,
	e.Event_type EVENT_TYPE,
	e.Event_subtype EVENT_SUBTYPE,
	e.Event_location EVENT_LOCATION,
	l.city EVENT_CITY,
	l.state EVENT_STATE,
	l.country EVENT_COUNTRY,
	e.Event_start_time EVENT_START_TIME,
	e.Event_end_time EVENT_END_TIME
FROM Event e
LEFT JOIN Location l
ON e.Event_location_ID = l.location_ID