DROP TABLE Tag;
ALTER TABLE Photo DROP CONSTRAINT PhotoAlbumFK; 
DROP TABLE Photo;
DROP TABLE Attended_program;
DROP TABLE Participate;
DROP TABLE Event;
DROP TABLE Message;
DROP TABLE Album;
DROP TABLE FB_User;
DROP TABLE Location;
DROP TABLE Eduation_program;
DROP TABLE Friendship;